'''
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle: n*(n+1)/2
Square: n*n
Pentagonal: n*(3*n-1)/2
Hexagonal: n*(2*n-1)
Heptagonal: n*(5*n-3)/2
Octagonal: n*(3*n-2)

The ordered set of three 4-digit numbers: 8128, 8281, 2882, has three interesting properties.

1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
2. Each polygonal type: triangle, square, and pentagonal, is represented by a different number in the set.
3. This is the only set of-digit numbers with this property.

Find the sum of the only ordered set of six cyclic-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
'''

def find4digit(fn):
	n = 0
	while fn(n) < 1000:
		n += 1

	res = []
	while (curr := fn(n)) < 10000:
		res.append(curr)
		n += 1
	return res

def findCycle(ns, cycle, digits):
	if len(cycle) == len(digits):
		if ns[0] // 100 == ns[-1] % 100:
			return True
		return False

	for i in range(len(digits)):
		if i in cycle: continue
		for d in digits[i]:
			if d // 100 == ns[-1] % 100:
				ns.append(d)
				cycle.add(i)
				if (findCycle(ns, cycle, digits)):
					return True
				cycle.remove(i)
				ns.pop()
	return False



triangle = lambda n: n*(n+1)//2
square = lambda n: n*n
pentagonal = lambda n: n*(3*n-1)//2
hexagonal = lambda n: n*(2*n-1)
heptagonal = lambda n: n*(5*n-3)//2
octagonal = lambda n: n*(3*n-2)

digits = [
	find4digit(triangle),
	find4digit(square),
	find4digit(pentagonal),
	find4digit(hexagonal),
	find4digit(heptagonal),
	find4digit(octagonal),
]


cycle = set()
i = 0
while len(cycle) < len(digits):
	cycle = set()
	cycle.add(0)
	print(f"Try: {digits[0][i]}")
	ns = [digits[0][i]]
	findCycle(ns, cycle, digits)
	i += 1

print(sum(ns), ns)
